version: '3.1'

services:
  postgres:
    image: postgres:16.1
    environment:
      - POSTGRES_DB=accounting-ilab
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - 5432:5432

